import {useEffect,useState} from 'react';
import {defaultFeatures} from '../../shared/features.js';
import './feature-settings.css';
const featureGroups=[['Payments',[['cash','Banknotes','Accept cash payments.'],['coin','Coins','Accept coin payments.'],['promptpay','PromptPay / QR','Show QR at checkout. Your payment provider must also be configured.']]],['Kiosk functions',[['ordering','Accept new orders','Turn off to pause new purchases.'],['screensaver','Screensaver','Show the idle display after inactivity.'],['animations','Animations','Product movement, background motion and purchase effects.'],['clock','Clock','Show the current time in the header.'],['slot_labels','Slot labels','Show product locations such as A1.']]]];
export default function AdminSettings({settings,api,onSaved,onPasswordChanged}){
 const [form,setForm]=useState(settings),[text,setText]=useState(JSON.stringify(settings.ui_text_json,null,2)),[file,setFile]=useState(null),[password,setPassword]=useState({current_password:'',new_password:''}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{setForm(settings);setText(JSON.stringify(settings.ui_text_json,null,2));},[settings]);
 const features={...defaultFeatures,...form.features};
 const changeFeature=(key,value)=>setForm(f=>({...f,features:{...defaultFeatures,...f.features,[key]:value}}));
 const change=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function save(e){e.preventDefault();setBusy(true);setMessage('');try{const ui_text_json=JSON.parse(text);let store_logo=form.store_logo;if(file){const data=new FormData();data.append('image',file);store_logo=(await api('/upload',{method:'POST',body:data})).image_url;}await api('/settings',{method:'PUT',body:{store_logo,ui_text_json,timezone:form.timezone,promptpay_id:form.promptpay_id,features,idle_seconds:form.idle_seconds??60}});setFile(null);setMessage('Settings saved. The kiosk refreshes within 10 seconds.');await onSaved();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function changePassword(e){e.preventDefault();setBusy(true);try{await api('/password',{method:'PUT',body:password});onPasswordChanged();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <div className="settings-grid"><form className="a-panel" onSubmit={save}><h2>Kiosk appearance & payments</h2><div className="feature-settings">{featureGroups.map(([title,items])=><fieldset key={title}><legend>{title}</legend>{items.map(([key,label,description])=><label className="feature-toggle" key={key}><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" role="switch" checked={features[key]} onChange={e=>changeFeature(key,e.target.checked)}/></label>)}</fieldset>)}<label>Screensaver delay (seconds)<input type="number" min={15} max={3600} required disabled={!features.screensaver} value={form.idle_seconds??60} onChange={e=>change('idle_seconds',e.target.value===''?'':Number(e.target.value))}/></label><p className="muted">Changes apply after Save settings. Keep at least one payment method on while ordering is enabled. QR setup is retained when switched off.</p></div><label>Store logo{form.store_logo&&<img className="logo-preview" src={form.store_logo} alt="Current store logo"/>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files[0]||null)}/></label><button type="button" onClick={()=>{change('store_logo','');setFile(null);}}>Remove logo</button><label>Timezone<input required value={form.timezone} onChange={e=>change('timezone',e.target.value)} placeholder="Asia/Bangkok"/></label><label>PromptPay ID<input inputMode="numeric" value={form.promptpay_id} onChange={e=>change('promptpay_id',e.target.value)} placeholder="Mobile number, tax ID, or wallet ID" pattern="(0[0-9]{9}|[0-9]{13}|[0-9]{15})?"/></label><p className="muted">QR generation is local. Payment confirmation comes from staff or a trusted payment adapter.</p><label>UI text / translations (JSON)<textarea spellCheck="false" rows={16} value={text} onChange={e=>setText(e.target.value)}/></label><button className="a-primary" disabled={busy}>Save settings</button>{message&&<p role="status">{message}</p>}</form><form className="a-panel" onSubmit={changePassword}><h2>Admin password</h2><label>Current password<input type="password" autoComplete="current-password" required value={password.current_password} onChange={e=>setPassword(p=>({...p,current_password:e.target.value}))}/></label><label>New password / PIN<input type="password" autoComplete="new-password" minLength={4} maxLength={128} required value={password.new_password} onChange={e=>setPassword(p=>({...p,new_password:e.target.value}))}/></label><button disabled={busy}>Update password</button><p className="muted">All admin sessions are signed out after a password change.</p></form></div>;
}
