import {useCallback,useEffect,useState} from 'react';
import {LayoutDashboard,Package,Settings,Cpu,LogOut,ShoppingBag,Plus,Pencil,Trash2,Zap,RefreshCw,ExternalLink} from 'lucide-react';
import {request,money} from './api';
import AdminSettings from './AdminSettings';
import Modal from './Modal';
export default function AdminDashboard(){
 const [token,setToken]=useState(()=>sessionStorage.getItem('vending-admin-v2')||''),[password,setPassword]=useState(''),[tab,setTab]=useState('Overview'),[data,setData]=useState(null),[settings,setSettings]=useState(null),[products,setProducts]=useState([]),[hardware,setHardware]=useState(null),[editing,setEditing]=useState(null),[file,setFile]=useState(null),[review,setReview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const logout=useCallback(()=>{sessionStorage.removeItem('vending-admin-v2');setToken('');setData(null);},[]);
 const api=useCallback(async(path,options={})=>{try{return await request(path,{...options,token});}catch(e){if(e.status===401)logout();throw e;}},[token,logout]);
 const refresh=useCallback(async()=>{const [s,p,h]=await Promise.all([api('/stats'),api('/products'),api('/hardware')]);setData(s);setProducts(p);setHardware(h);},[api]);
 const loadSettings=useCallback(async()=>setSettings(await api('/settings')),[api]);
 useEffect(()=>{if(!token)return;refresh().catch(e=>setError(e.message));loadSettings().catch(e=>setError(e.message));const timer=setInterval(()=>refresh().catch(e=>setError(e.message)),2500);return()=>clearInterval(timer);},[token,refresh,loadSettings]);
 async function act(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const edit=p=>{setFile(null);setEditing({...p,price:String(p.price/100)});};
 async function save(e){e.preventDefault();act(async()=>{let image_url=editing.image_url;if(file){const f=new FormData();f.append('image',file);image_url=(await api('/upload',{method:'POST',body:f})).image_url;}await api('/products'+(editing.id?'/'+editing.id:''),{method:editing.id?'PUT':'POST',body:{...editing,price:Math.round(Number(editing.price)*100),stock:Number(editing.stock),image_url}});setEditing(null);await refresh();});}
 const field=(k,v)=>setEditing(p=>({...p,[k]:v}));
 if(!token)return <main className="admin-login"><form className="a-panel" onSubmit={e=>{e.preventDefault();act(async()=>{const r=await request('/login',{method:'POST',body:{password}});sessionStorage.setItem('vending-admin-v2',r.token);setToken(r.token);setPassword('');});}}><ShoppingBag size={38}/><h1>Hello, keeper of treats.</h1><p className="muted">Sign in to your machine dashboard.</p><label>Password / PIN<input autoFocus type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="a-error" role="alert">{error}</p>}<button className="a-primary" disabled={busy}>Unlock dashboard</button><a href="/">Back to kiosk</a></form></main>;
 return <div className="admin-shell"><aside><div className="a-brand"><ShoppingBag/><strong>TK control room</strong></div><nav>{[['Overview',LayoutDashboard],['Products',Package],['Hardware',Cpu],['Settings',Settings]].map(([name,Icon])=><button key={name} className={tab===name?'selected':''} onClick={()=>setTab(name)}><Icon size={19}/>{name}</button>)}</nav><a href="/" target="_blank" rel="noreferrer"><ExternalLink size={18}/>Open kiosk</a><button onClick={()=>act(async()=>{await api('/logout',{method:'POST'});logout();})}><LogOut size={18}/>Sign out</button></aside><main className="admin-main"><header><div><p className="eyebrow">MACHINE ADMIN</p><h1>{tab}</h1></div><div className="a-header-actions"><span className="status-pill">{hardware?.mode==='mock'?'Simulator':hardware?.connected?'Controller online':'Offline'}</span><button aria-label="Refresh" disabled={busy} onClick={()=>act(refresh)}><RefreshCw size={18}/></button></div></header>{error&&<p className="a-error" role="alert">{error}</p>}{notice&&<p className="a-notice" role="status">{notice}</p>}{!data?<p>Loading…</p>:<>
 {!!data.active_orders.length&&<section className="a-panel active-orders"><h2>Active orders</h2>{data.active_orders.map(tx=><article key={tx.id}><div><b>{tx.id.slice(0,8)} · {tx.status}</b><p>{tx.items.map(i=>`${i.slot} × ${i.qty}`).join(' · ')} — {money(tx.paid_amount)} / {money(tx.total_amount)}</p></div>{tx.status==='awaiting_payment'&&<button disabled={busy} onClick={()=>{if(window.confirm('Have you verified that the full payment was actually received? This starts the motors.'))act(async()=>{await api(`/orders/${tx.id}/confirm-payment`,{method:'POST'});await refresh();});}}>Confirm received payment</button>}{['uncertain','awaiting_payment'].includes(tx.status)&&<button disabled={busy} onClick={()=>setReview({id:tx.id,delivered:tx.items.map(i=>({slot:i.slot,qty:0,max:i.qty}))})}>Reconcile / refund</button>}</article>)}</section>}
 {tab==='Overview'&&<><div className="a-metrics"><section className="a-panel"><p>Sales after recorded refunds due</p><strong>{money(data.total_sales)}</strong></section><section className="a-panel"><p>Items delivered</p><strong>{data.items_sold}</strong></section><section className="a-panel"><p>Low stock slots</p><strong>{data.low_stock.length}</strong></section></div><section className="a-panel"><h2>Low stock</h2><div className="stock-tags">{data.low_stock.length?data.low_stock.map(p=><button key={p.id} onClick={()=>edit(p)}>{p.slot} · {p.name} · {p.stock} left</button>):<p className="muted">Stock levels look good.</p>}</div></section><section className="a-panel"><h2>Recent transactions</h2><div className="table-scroll"><table><thead><tr><th>Order / time</th><th>Items</th><th>Payment</th><th>Total</th><th>Status</th><th>Refund due</th></tr></thead><tbody>{data.recent_transactions.map(tx=><tr key={tx.id}><td>{tx.id.slice(0,8)}<small>{new Date(tx.created_at).toLocaleString()}</small></td><td>{tx.items.map(i=>`${i.name} × ${i.qty}`).join(', ')}</td><td>{tx.payment_method}</td><td>{money(tx.total_amount)}</td><td>{tx.status}</td><td>{money(tx.refund_due)}</td></tr>)}</tbody></table>{!data.recent_transactions.length&&<p className="muted">No transactions yet.</p>}</div></section></>}
 {tab==='Products'&&<div className="a-products">{settings?.slots.map(slot=>{const p=products.find(p=>p.slot===slot);return <section className="a-panel minimal-product" key={slot}><div className="a-product-top"><b>{slot}</b><span className={p&&p.stock<=3?"product-stock-low":""}>{p?`${p.stock} in stock`:'Empty slot'}</span></div>{p?<><div className="a-product-image w-full h-40 rounded-xl p-4 flex items-center justify-center">{p.image_url?<img src={p.image_url} alt={p.name} className="w-full h-full object-contain"/>:<Package size={36}/>}</div><div className="product-summary"><h2>{p.name}</h2><p>{money(p.price)}</p></div><div className="a-actions product-tools"><button onClick={()=>edit(p)}><Pencil size={16}/>Edit</button><button aria-label={`Delete ${p.name}`} disabled={busy} onClick={()=>{if(window.confirm(`Remove ${p.name}?`))act(async()=>{await api('/products/'+p.id,{method:'DELETE'});await refresh();});}}><Trash2 size={17}/></button></div></>:<button className="empty-product" onClick={()=>edit({slot,name:'',price:100,stock:0,type:'',color:'#cce5ff',image_url:''})}><Plus/>Add product</button>}</section>;})}</div>}
 {tab==='Settings'&&settings&&<AdminSettings settings={settings} api={api} onSaved={loadSettings} onPasswordChanged={logout}/>}
 {tab==='Hardware'&&<><section className="a-panel"><h2>ESP32-S3 · USB serial</h2><p>{hardware?.blocked?'Locked: reconcile the order, power-cycle the ESP32, then restart the API.':hardware?.busy?'Dispensing…':'Ready for the next command.'}</p><p className="muted">A test physically dispenses one item and reduces assigned stock.</p><div className="motor-buttons">{settings?.slots.map(slot=><button key={slot} disabled={busy||!hardware?.connected||hardware?.blocked||!!data.active_orders.length} onClick={()=>{if(window.confirm(`Run motor ${slot} and dispense one item?`))act(async()=>{await api('/hardware/test',{method:'POST',body:{slot}});await refresh();});}}><Zap size={18}/>Test {slot}</button>)}</div></section><section className="a-panel"><h2>Serial logs</h2><pre>{hardware?.logs.map(l=>`${l.timestamp} [${l.direction}] ${l.message}`).join('\n')||'No serial activity yet.'}</pre></section></>}
 </>}</main>{editing&&<Modal label="Edit product" onClose={()=>!busy&&setEditing(null)} className="admin-modal"><form onSubmit={save}><h2>{editing.id?'Edit':'Add'} product · {editing.slot}</h2><label>Name<input autoFocus required maxLength={80} value={editing.name} onChange={e=>field('name',e.target.value)}/></label><div className="form-row"><label>Price (THB)<input type="number" min="0.01" max="10000" step="0.01" required value={editing.price} onChange={e=>field('price',e.target.value)}/></label><label>Stock<input type="number" min="0" max="1000" step="1" required value={editing.stock} onChange={e=>field('stock',e.target.value)}/></label></div><div className="form-row"><label>Type<input value={editing.type} onChange={e=>field('type',e.target.value)}/></label><label>Accent<input type="color" value={editing.color} onChange={e=>field('color',e.target.value)}/></label></div><label>Image (max 5 MB)<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files[0]||null)}/></label>{error&&<p className="a-error">{error}</p>}<div className="a-actions"><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button><button className="a-primary" disabled={busy}>Save product</button></div></form></Modal>}{review&&<Modal label="Reconcile order" onClose={()=>!busy&&setReview(null)} className="admin-modal"><form onSubmit={e=>{e.preventDefault();if(window.confirm('Confirm these physically delivered quantities? Restore undelivered stock and record the refund due?'))act(async()=>{const r=await api(`/orders/${review.id}/resolve`,{method:'POST',body:{delivered:review.delivered.map(({slot,qty})=>({slot,qty:Number(qty)}))}});setReview(null);setNotice(`Reconciled. Refund due: ${money(r.refund_due)}. Pay refunds through your payment system. For hardware faults, power-cycle controller and restart API.`);await refresh();});}}><h2>Actual delivered quantities</h2><p>Inspect the chute and stock. Do not assume the sensor receipt is complete.</p>{review.delivered.map((d,index)=><label key={d.slot}>{d.slot} (ordered {d.max})<input required type="number" min="0" max={d.max} step="1" value={d.qty} onChange={e=>setReview(r=>({...r,delivered:r.delivered.map((v,i)=>i===index?{...v,qty:e.target.value}:v)}))}/></label>)}{error&&<p className="a-error">{error}</p>}<div className="a-actions"><button type="button" onClick={()=>setReview(null)}>Cancel</button><button disabled={busy} className="a-primary">Confirm quantities</button></div></form></Modal>}</div>;
}
